# Generated by Django 3.2.10 on 2021-12-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arunpriya', '0002_scient'),
    ]

    operations = [
        migrations.CreateModel(
            name='cricket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('na', models.CharField(max_length=250)),
                ('im', models.ImageField(upload_to='pic')),
                ('des', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='scient',
        ),
    ]
